name: moldesign-demo
channels:
  - defaults
  - conda-forge
dependencies:
# Core dependencies
  - python==3.11.*
  - pip

# Dependencies from the molecular design app
  - scikit-learn
  - rdkit
  - xtb-python==22.1
  - redis
  - psutil

# Pip install Parsl and the local functions
  - pip:
      - -e .
      - parsl
      - ase
      - colmena
